version: '3'

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=d120-coni
      - POSTGRES_PASSWORD=d120-coni
      - POSTGRES_DB=coniunctio
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U d120-coni -d coniunctio"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
volumes:
  db: